### ISSUE TITLE
请问一下，这个错误是什么意思   ：AttributeError: module 'torchaudio' has no attribute 'load_wav'

### ISSUE THREAD

**Issue by zhuxu2000** [yang123qwe/end2end_chinese_speech_recognition#16]
Traceback (most recent call last):
  File "C:/语音识别/end2end_chinese_speech_recognition-master/main.py", line 32, in <module>
    result_ = main(path_)
  File "C:/语音识别/end2end_chinese_speech_recognition-master/main.py", line 15, in main
    inst_T = get_fu( path_ )
  File "C:/语音识别/end2end_chinese_speech_recognition-master/main.py", line 7, in get_fu
    _wavform, _ = ta.load_wav( path_ )
AttributeError: module 'torchaudio' has no attribute 'load_wav'

**Comment by zhuxu2000** [comment]
当前环境问题，将load_wav()改为load()
