### ISSUE TITLE
跑不起来啊哥们 Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by h3clikejava** [yang123qwe/end2end_chinese_speech_recognition#5]
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    num_wor = np.load('models/dic.dic.npy').item()
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/format.py", line 727, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by yang123qwe** [comment]
main.py 的27行改为


num_wor = np.load('models/dic.dic.npy',&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;allow_pickle=True&nbsp;).item()

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月4日(周五) 晚上6:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yang123qwe/end2end_chinese_speech_recognition] 跑不起来啊哥们 Object arrays cannot be loaded when allow_pickle=False (#5)




 
Traceback (most recent call last):
 File "main.py", line 27, in 
 num_wor = np.load('models/dic.dic.npy').item()
 File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
 pickle_kwargs=pickle_kwargs)
 File "/opt/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/format.py", line 727, in read_array
 raise ValueError("Object arrays cannot be loaded when "
 ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by CLC2019** [comment]
将allow_pickle设为True就可以
num_wor = np.load('models/dic.dic.npy',allow_pickle=True).item()
